"use client"
import Navbar from '@/components/Navbar'
import '@/styles/globals.css'

import { ThemeProvider } from 'next-themes'


export const metadata = {
  title: 'Renes Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider enableSystem={true} attribute='class'>
        <Navbar/>
        {children}
        </ThemeProvider>
        </body>
    </html>
  )
}
